language: clojure
lein: lein2
script: lein2 cljsbuild test slimerjs
jdk:
  - openjdk7
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "24.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/v0.9/0.9.0/slimerjs-0.9.0.zip"
  - "unzip slimerjs-0.8.3.zip"
  - "mv slimerjs-0.8.3 ./slimerjs"